import './css/style.css';

import { Inter } from 'next/font/google';
import localFont from 'next/font/local';

import Header from '@/components/ui/header';
import Spotlight from '@/components/spotlight';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const nacelle = localFont({
  src: [
    {
      path: '../public/fonts/nacelle-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/nacelle-italic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../public/fonts/nacelle-semibold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/nacelle-semibolditalic.woff2',
      weight: '600',
      style: 'italic',
    },
  ],
  variable: '--font-nacelle',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${nacelle.variable} font-inter bg-gray-950 text-base text-gray-200 antialiased`}
      >
        <Spotlight>
          <div className="flex min-h-screen flex-col overflow-hidden rounded-2xl p-px before:pointer-events-none before:absolute before:-top-40 before:-left-40 before:z-10 before:h-80 before:w-80 before:translate-x-[var(--mouse-x)] before:translate-y-[var(--mouse-y)] before:rounded-full before:bg-indigo-500/80 before:opacity-0 before:blur-3xl before:transition-opacity before:duration-500 group-hover:before:opacity-100 after:pointer-events-none after:absolute after:-top-48 after:-left-48 after:z-30 after:h-64 after:w-64 after:translate-x-[var(--mouse-x)] after:translate-y-[var(--mouse-y)] after:rounded-full after:bg-indigo-500 after:opacity-0 after:blur-3xl after:transition-opacity after:duration-500 hover:after:opacity-20 supports-[overflow:clip]:overflow-clip">
            <Header />
            {children}
          </div>
        </Spotlight>
      </body>
    </html>
  );
}
